targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swaggers"
          output_folder: "lib/models/"
          # with_base_url: false
          with_converter: true
          use_required_attribute_for_header: false
          additional_headers: 
            - "Authorization"
